# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MenuTag' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MenuTag
    pod 'SVProgressHUD'
    pod 'QuadratTouch'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AWSS3'
end
